version: "3"

# virtual volume
volumes:
  build:

services:
  {{ _.kebabCase(package.name) }}-watcher:
    image: "${IMAGE_PREFIX}watcher-image:${IMAGE_TAG:-latest}"
    env_file:
      - .env
    depends_on:
      - {{ _.kebabCase(package.name) }}-service
    volumes:
      - .:/code
      - build:/code/build
    command: watch

  {{ _.kebabCase(package.name) }}-service:
    image: "${IMAGE_PREFIX}{{ _.kebabCase(package.name) }}-image:${IMAGE_TAG:-latest}"
    env_file:
      - .env
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8000"
    volumes:
      - build:/code/build
    networks: {{ _.kebabCase(package.name) }}
      - default
    command: dev
