version: "3"

services:
  cdc-auth:
    image: "{{ package.name }}"
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8000"
networks:
  default:
    external:
      name: {{ package.name }}-network
